import 'package:flutter_application_2/index.dart';
import 'package:flutter_application_2/localization/app_string_keys.dart';
import 'package:flutter_application_2/localization/index.dart';

const Map<String, String> localizations = {
  signUp: 'Sign up',
  login: 'Login',
  welcome: 'Welcome!',
  welcomeBack: 'Welcome Back',
  signUpTitle: 'Please register for an account',
  hintText: 'johndoe@gmail.com',
  emailAddress: 'Email Address',
  emptyError: 'Please enter some text',
  passwordHintText: 'Jo123*&00gts',
  password: 'Password',
  submit: 'Submit',
  passwordValidationMessage:
      'Password should contain at least 8 characters: 1 lowercase,\n digit and or a symbol, and 1 uppercase character',
  signUpWith: 'or Sign up with',
  alreadyHaveAccount: 'Already have an account?',
  signUpTextRichPartOne: 'By signing into StudyM8 you agree to our\n',
  signUpTextRichPartTwo: 'Terms of Service',
  and: 'and',
  privacyPolicy: 'Privacy Policy',
  loginTitle: 'Please login to your account',
  loginWith: 'or Login with',
  toSignUpTextPartOne: 'New to StudyM8 this?',
  createAccount: 'Create Account',
  setUpProfile: 'Set up profile',
  profileHintName: 'Benjamin|',
  profileTextFieldHelpText: '*Username should contain numbers',
  textContinue: 'Continue',
  myCourses: 'My Courses',
  ongoing: 'Ongoing',
  completed: 'Completed',
  certificates: 'Certificates',
  projectTitle: 'Study8',
  homeRoute: '/',
  singlePopularCourseRoute: '/single_popular_course_route',
  enrollPaymentRoute: '/enroll_payment_options',
  coursesRoute: '/courses',
  enrollCourse: 'Enroll Course',
  selectPaymentMethod: 'Please select a payment method',
  clipPathGroupImgPath: 'assets/images/clip_path_group_3.png',
  getYouInTitle: 'Let\'s get you in',
  or: 'Or',
  signInWithPassword: 'Sign in with password',
  skip: 'Skip',
  next: 'Next',
  of: 'of',
  study8: 'StudyM8',
  readMoreText: 'Read More',
  home: 'Home',
  profile: 'Profile',
  passwordRegExp:
      r'^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[!@#\$&*~]).{8,}\$',
  browser: 'Browser',
  singleCourseRoute: '/single_course',
  lectures: 'Lectures',
  more: 'More',
  goodMorning: 'Good Morning',
  benjamin: 'Benjamin',
  search: 'Search',
  makeProgressListTitle: 'Keep learning to make progress',
  popularCourses: 'Popular Courses',
  seeAll: 'See all',
  unenroll: 'Unenroll',
  resetDeadlines: 'Reset Deadlines',
  continueCourse: 'Continue Course',
  priceRange: 'Price range',
  filter: 'Filter',
  category: 'Category',
  raiting: 'Rating',
  clearFilter: 'Clear filter',
  applyFilter: 'Apply filter',
  allCourses: 'All Courses',
  aboutThisCourse: 'About this course',
  skillsYouWillGain: 'Skills you will gain',
  courseInstructor: 'Course Instructor',
  enrollCourseRoute: '/enroll_course',
  enterYourPin: 'Enter your pin to confirm payment',
  successfullyEnrolled: 'Successfully enrolled',
  viewCourse: 'View Course',
  paymentReceipt: 'Payment Receipt',
  successfullyEnrolledImg: 'assets/images/success_img.png',
  searchRoute: '/search_route',
  recent: 'Recent',
  clearAll: 'Clear All',
  resultFor: 'Results for',
  notFounded: '0 Found',
  smileImg: 'assets/images/not_found_smile.png',
  notFound: 'Not Found',
  notFoundDescription:
      'Sorry the keyword you entered\n cannot be found, please check again or\n search with another term',
};
